name: mbti-type-detector
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.8.5
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libexpat=2.6.2
  - libffi=3.4.4
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.12.5
  - python_abi=3.12
  - pywin32=306
  - pyzmq=26.1.0
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.46.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.0
  - zlib=1.3.1
  - pip:
      - accelerate==0.33.0
      - aiohappyeyeballs==2.3.5
      - aiohttp==3.10.3
      - aiosignal==1.3.1
      - attrs==24.2.0
      - black==24.8.0
      - bleach==6.1.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - datasets==2.21.0
      - dill==0.3.8
      - filelock==3.15.4
      - flake8==7.1.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - ghp-import==2.1.0
      - huggingface-hub==0.24.5
      - idna==3.7
      - isort==5.13.2
      - jinja2==3.1.4
      - kaggle==1.6.17
      - loguru==0.7.2
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mbti-personality-detector==0.0.1
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - mkdocs==1.6.0
      - mkdocs-get-deps==0.2.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - networkx==3.3
      - numpy==1.26.4
      - pandas==2.2.2
      - pathspec==0.12.1
      - peft==0.12.0
      - protobuf==5.27.3
      - pyarrow==17.0.0
      - pycodestyle==2.12.1
      - pyflakes==3.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-slugify==8.0.4
      - pytz==2024.1
      - pyyaml==6.0.2
      - pyyaml-env-tag==0.1
      - regex==2024.7.24
      - requests==2.32.3
      - rich==13.7.1
      - safetensors==0.4.4
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - sympy==1.13.2
      - text-unidecode==1.3
      - tokenizers==0.19.1
      - torch==2.4.0
      - tqdm==4.66.5
      - transformers==4.44.0
      - typer==0.12.3
      - tzdata==2024.1
      - urllib3==2.2.2
      - watchdog==4.0.2
      - webencodings==0.5.1
      - win32-setctime==1.1.0
      - xxhash==3.4.1
      - yarl==1.9.4
